language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
before_install:
  - npm install
install:
  - npm install
cache:
  npm: true
  directories:
    - node_modules
script:
  - npm run build
  - npm test -- --coverage
