language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
before_install:
   - npm i -g npm@version-7.10.0
install:
  - npm
cache:
  npm: true
  directories:
    - node_modules
script:
  - npm test --coverage
  - npm run build
