language: node_js
node_js:
  - "stable"
cache:
directories:
  - client/node_modules
before_install:
  - npm install
install:
  - cd client && npm install
cache:
  npm: true
  directories:
    - client/node_modules
script:
  - npm run pretest
  - npm run test -- --coverage
  - npm run build