language: node_js
node_js:
  - "stable"
cache:
directories:
  - travis cache --delete
  - clients/node_modules
env:
  global:
    - CC_TEST_REPORTER_ID=6c601813d98c22657b50d53d3899ca8402fd611cb7001917ae4931fc263027da
before_install:
  - npm install
install:
  - cd client && npm install
cache:
  npm: false
  directories:
    - travis cache --delete
    - client/node_modules
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - npm run pretest
  - npm run test
  - npm run build
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
notifications:
  email:false