version: 2
jobs:
  build:
    environment:
    CC_TEST_REPORTER_ID: 6c601813d98c22657b50d53d3899ca8402fd611cb7001917ae4931fc263027da
    docker:
      - image: circleci/node:11.9.0
    working_directory: ~/swapi_server/client
    steps:
      - checkout
      - restore_cache: # special step to restore the dependency cache
          key: dependency-cache-{{ checksum "client/package.json" }}
      - run:
          name: Setup Dependencies
          command: cd client && npm install
      - run:
          name: Setup Code Climate test-reporter
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
            ./cc-test-reporter before-build
      - save_cache: # special step to save the dependency cache
          key: dependency-cache-{{ checksum "client/package.json" }}
          paths:
            - client/node_modules
      - run: # run tests now
          name: Run Test and Coverage
          command: |
            cd client && npm run pretest
            npm run test -- --coverage
      - run: #  Send coverage to Code Climate
          command: |
            ./cc-test-reporter after-build format-coverage -t lcov -p /coverage/lcov.info out --exit-code $?
