version: 2.1

jobs:
  test:
    docker:
      - image: cimg/node:15.1
    working_directory: ~/swapi_server/
    steps:
      - checkout
      - restore_cache:
          # See the configuration reference documentation for more details on using restore_cache and save_cache steps
          # https://circleci.com/docs/2.0/configuration-reference/?section=reference#save_cache
          keys:
            - node-deps-v1-{{ .Branch }}-{{checksum "client/package.json"}}
      - run:
          name: install packages
          command: cd client && npm install
      - save_cache:
          key: node-deps-v1-{{ .Branch }}-{{checksum "client/package.json"}}
          paths:
            # - ~ cd client && /.npm
            - client/node_modules
      - run: # run pretests now
          name: Run Pretest
          command: |
            cd client && npm run pretest
      - run: # run tests now
          name: Run Test
          command: |
            cd client && npm test
workflows:
  orb-free-workflow:
    jobs:
      - test
notifications: email:false
